### ISSUE TITLE
Missing required parameter: client_id

### ISSUE THREAD

**Issue by spattinson** [quadule/knobby#1]
When I visit http://knobby.local it redirects to https://accounts.spotify.com/authorize/?response_type=code&scope=user-read-private+user-read-currently-playing+user-read-playback-state+user-modify-playback-state+playlist-read-private+user-library-read+user-follow-read+user-follow-modify&show_dialog=true&redirect_uri=http%3A%2F%2Fknobby.Accept-Ranges:%20none and in the browser the response is **"Missing required parameter: client_id"**

meanwhile in the serial monitor it repeats **"Need access token"**

Maybe the data.json is not building correctly? All it contains is {"users":[]} or does that get populated later?

Thanks for posting this is looks great!

**Comment by quadule** [comment]
Thanks for trying it out and reporting this!

I think I ran into this problem before and filed this PR: https://github.com/me-no-dev/ESPAsyncWebServer/pull/834 That redirect URI is overflowing the buffer used for the response so the `client_id` param isn't getting appended. The data.json is correct; it does get populated after authorizing with Spotify.

Until ESPAsyncWebServer is updated, you'll have to apply my patch to your copy of the library in `~/.platformio/lib`. I also plan to release compiled firmware with this fixed after I've done #2 and #3.

**Comment by spattinson** [comment]
Thanks for the fast response. That was the issue. I'm seeing the api requests in the serial monitor now.
Now I need to wait for the encoder to arrive.
Not needing a settings file would be cool.
Great work thanks!

**Comment by quadule** [comment]
I've changed platformio.ini to use my own fork of ESPAsyncWebServer for now, so this should no longer be an issue.
