### ISSUE TITLE
Only playlist knobby shows is "liked songs"

### ISSUE THREAD

**Issue by muzerious** [quadule/knobby#16]
recently knobby will only show my "liked songs" playlist. previously i was able to access and scroll through all my saved playlists. I am running the latest version. 

even if I like or save new playlists, they dont show up.

**Comment by brianmgr** [comment]
I had the same issue when loading the vanilla firmware from https://setup.knobby.net/. I would click/scroll to "playlists" and only see "liked songs".

I figured it might be an issue with the API call to the `me/playlists` Spotify API endpoint, so I tried opening the code in PlatformIO and first uploading the firmware manually before playing with the API call [here](https://github.com/quadule/knobby/blob/87f96e597b0615fe28c77ec0df1ae711d5787359/src/main.cpp#L3169). But I uploaded the plain old firmware with PlatformIO and the Playlist functionality just worked ¯\_(ツ)_/¯. I now see 51 playlists (the firmware looks like it caps it at 50 with `uint16_t limit = 50;` at line 3159)

So I don't know if the official current version on the setup site is out of date or different than what's in the repo maybe? But build/upload with PlatformIO seemed to work for me!

**Comment by quadule** [comment]
Sorry for the radio silence! Spotify seems to have made a small breaking change to the playlists API endpoint[^1] which broke this menu. I fixed the issue on main but never got around to publishing a release until now: https://github.com/quadule/knobby/releases/tag/2024.11.24

[^1]: When specifying `fields` to include in the API response, pagination attributes like `total` are no longer included automatically.
