### ISSUE TITLE
I'm getting a "Certificate verification failed" error

### ISSUE THREAD

**Issue by lmore377** [quadule/knobby#5]
I keep getting this error after I click agree on the spotify page. I get this with the latest release (knobby-1.0-pre) and the latest git commit. 

```
[I][ArduinoOTA.cpp:130] begin(): OTA server at: knobby.local:3232
[I][main.cpp:396] loop(): [1638] Connected to wifi with IP address 192.168.1.176
[I][main.cpp:159] operator()(): [11760] server.on /
[I][main.cpp:169] operator()(): [11818] server.on /authorize
[I][main.cpp:1809] spotifyGetToken(): [15457] POST /api/token
[E][ssl_client.cpp:36] _handle_error(): [start_ssl_client():202]: (-9984) X509 - Certificate verification failed, e.g. CRL, CA or signature check failed
[E][WiFiClientSecure.cpp:132] connect(): start_ssl_client: -9984
[W][HTTPClient.cpp:1317] returnError(): error(-1): connection refused
[W][HTTPClient.cpp:1317] returnError(): error(-4): not connected
```

**Comment by lmore377** [comment]
I managed to get it to work by copying the cert in spotify,h from [this commit](https://github.com/quadule/knobby/commit/9279bf0c23c715bbc510ea6bf813796843e5db69) to the latest commit. 

On an unrelated note, I picked up a generic alps rotary encoder from ebay (they seem to be the most common and readily available) and while it does work, I have to turn the knob 2 ticks to get it to move in either direction. Do you know if there's any way to get it to work? I tried the other attach methods in the ESP32Encoder library but they just make it worse.

**Comment by quadule** [comment]
Glad to hear you got it working. Spotify changed their certificate last week but it should be fixed now. I’ve pulled and rereleased `v1.0-pre` a few times so I’m guessing you had an old one. I’ll have a new one pushed shortly.

For the rotary encoder issue, try changing [`ROTARY_ENCODER_PULSE_COUNT` in platformio.ini](https://github.com/quadule/knobby/blob/ab1afc59ccce196b091cbbd77e43242a2168cd33/platformio.ini#L53) to 2. I may move that option to data.json so it won’t require a custom build.

**Comment by lmore377** [comment]
It works fine now without any modification and changing the pulse count worked too. Thanks!

**Comment by quadule** [comment]
> Liking isn't working but adding user-library-modify to the scopes makes it work.

Thanks for catching that! Looks like it was only working for me while using the same Spotify account that registered the application for their API.

**Comment by lmore377** [comment]
I'm having this weird issue where the knobby will go to sleep and won't wake up at all unless I open it and press the reset button or plug it into USB and unplug it (it doesn't have to be plugged in for long at all. Literally less than a second gets it booting) but this only happens on battery. On USB it works perfectly fine and I'm about 90% sure it's not the battery because when it's in this state, the battery still has voltage and when I get it back on it shows that the battery still has a full charge. Do you think my board is faulty or is there something wrong with the code?

**Comment by lmore377** [comment]
https://photos.app.goo.gl/YeP6PZLAZp5y48tz5 I just want you to see how weird this is

**Comment by lmore377** [comment]
Soooo turns out it was a hardware problem. I have 2 of the esp modules. On the first one the screen was broken but I decided to transfer the screen from the 2nd one to the first one and now it works fine.

**Comment by quadule** [comment]
Ok, closing this then. Glad to hear it's working for you now!
